---
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(readxl)
library(statR)

source(here::here("R/custom_fmt_number.R"))
```

Link (männlich): https://www.bfs.admin.ch/bfs/de/home/statistiken/katalog.assetdetail.36062345.html
Link (weiblich): https://www.bfs.admin.ch/bfs/de/home/statistiken/katalog.assetdetail.36062347.html

# Männliche Vornamen in der Schweiz

Bemerkung: Vornamen mit weniger als 3 Nennungen werden ausgeschlossen.

```{r}

vornamen_m <- read_csv("https://dam-api.bfs.admin.ch/hub/api/dam/assets/36062345/master") |> 
    select(-OBS_STATUS, -TIME_PERIOD) |> 
    mutate(geschlecht = "m") |>
    janitor::clean_names()

vornamen_w <- read_csv("https://dam-api.bfs.admin.ch/hub/api/dam/assets/36062347/master")|> 
    select(-OBS_STATUS, -TIME_PERIOD) |> 
    mutate(geschlecht = "w") |>
    janitor::clean_names()

vornamen <- vornamen_m |> 
    bind_rows(vornamen_w) |> 
    rename(vorname = firstname,
           geburtsjahr = yearofbirth,
           wert = value)

write_csv(vornamen, here::here("data/bfs-vornamen/bfs-vornamen-schweiz.csv"))
```

```{r}

### 

vornamen |>
    count(length = str_length(vorname), wt = wert) |> 
    ggplot(aes(x = factor(length), y = n)) +
    geom_col(width = 0.8, fill = zhpal$zhwebdataviz[[1]]) +
    # geom_text(aes(label = custom_fmt_number(n)),
    #           vjust = -0.5,
    #           size = 4) +
    geom_text(aes(label = custom_fmt_number(n)),
              vjust = -0.5,
              size = 3) +
    labs(x = "Anzahl Buchstaben",
         y = NULL,
         title = "Anzahl Buchstaben in Vornamen, Schweiz",
         subtitle = "Jahrgänge 1915 bis 2023") +
    scale_fill_manual() +
    theme_stat() +
    theme(
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank(),
        panel.grid.major.y = element_blank()
    ) 


vornamen |> 
    count(vorname, wt = wert) |> 
    arrange(n)

vornamen |> 
    filter(str_length(vorname) == 20) |> 
    count(vorname, geschlecht, wt = wert)

vornamen |> 
    mutate(first = str_sub(vorname, 1, 1),
           last = str_sub(vorname, -1, -1)) |> 
    count(last, geschlecht, wt = wert) |>
    group_by(geschlecht) |>
    mutate(prozent = n / sum(n) * 100) |> 
    arrange(desc(prozent))

ggplot(aes(x = reorder(last, n), y = n)) +
    geom_point() +
    coord_flip() +
    facet_wrap(~geschlecht) 


# Use stringr R package to identify observations where the last letter of the string is a capitalized I.
# https://www.perplexity.ai/search/use-stringr-r-package-to-ident-OXEjdKl8Swe2sjH_sJRtZA

vornamen |> 
    filter(str_detect(vorname, "I$"))

vornamen |> 
    group_by(geburtsjahr, geschlecht) |>
    summarize(sum_x = sum(str_detect(vorname, "x")),
              sum_y = sum(str_detect(vorname, "y"))) |> 
    pivot_longer(cols = c(sum_x, sum_y), names_to = "summe", values_to = "wert") |> 
    ggplot(aes(x = geburtsjahr, y = wert, color = geschlecht)) +
    geom_line() +
    facet_wrap(~summe)


```
