---
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(readxl)
```

Link: https://www.zh.ch/de/politik-staat/statistik-daten/datenkatalog.html#/datasets/1341@statistisches-amt-kanton-zuerich

#  Bevölkerungsbefragung im Kanton Zürich zur Zufriedenheit mit der Wohngemeinde 

```{r}

befragung <- read_csv(here::here("data/ktzh-bevoelkerungsbefragung-zufriedenheit/KTZH_00001341_00002759.csv")) 


codebook <- read_csv(here::here("data/ktzh-bevoelkerungsbefragung-zufriedenheit/KTZH_00001341_00002918.csv")) |> 
    rename(id = ...1)

codebook_frage7a1 <- codebook |> 
    filter(Variable %in% c("Frage7_A1", "geschlecht", "alter_koh", "gemeinde_groesse")) 

antwortskala_frage7a1 <- codebook_frage7a1 |> 
    filter(id == 59) |> 
    pull(Antwortskala)

# Dieser Code wurde mittels AI geschrieben: https://www.perplexity.ai/search/in-r-tidyverse-turn-the-follow-BpoeP_WIRkG4OSYznMjWyQ

code_antwort_frage7a1 <- str_split(antwortskala_frage7a1, ", ", simplify = TRUE) |> 
    as.vector() |> 
    as_tibble() |>
    rename(full_value = value) |>
    mutate(
        split_value = str_remove(full_value, "^\\S+\\s"),
        code = str_extract(full_value, "^\\S+"),
        split_value = str_replace_all(split_value, "\\s{2,}", " ")
    ) |>
    select(code, antwort = split_value) |> 
    filter(code != "NA") |> 
    mutate(code = as.numeric(code))

# Join um Code für Frage 7a mit Antwort zu verbinden

befragung_frage7a1 <- befragung |> 
    select(Frage7_A1, geschlecht, alter = alter_koh, gemeinde_groesse, bezirk_name = bezirk_name_kurz) |> 
    rename(code = Frage7_A1) |> 
    mutate(geschlecht = case_when(
        geschlecht == 1 ~ "männlich",
        geschlecht == 2 ~ "weiblich"
    ))  |> 
    mutate(gemeinde_groesse = case_when(
        gemeinde_groesse == ">100000" & bezirk_name == "Zürich" ~ "Zürich",
        gemeinde_groesse == ">100000" & bezirk_name == "Winterthur" ~ "Winterthur",
        TRUE ~ gemeinde_groesse)) |> 
    left_join(code_antwort_frage7a1) |> 
    select(-code) 

##

antwort_levels <- c("viel zu tief", 
                    "eher zu tief", 
                    "gerade angemessen", 
                    "eher zu hoch", 
                    "viel zu hoch", 
                    "weiss nicht / keine Angabe")

alter_levels <- befragung_frage7a1 |>
    pull(alter) |> 
    unique() |> 
    sort() 

befragung_frage7a1 |> 
    pull(gemeinde_groesse) |> 
    unique() |> 
    sort()

gemeinde_groesse_level <- c("<1000",
                            "1001 bis 2000",
                            "2001 bis 5000",
                            "5001 bis 10000",
                            "10001 bis 20000",
                            "20001 bis 50000",
                            "Winterthur",
                            "Zürich")

# Faktoriesierung der Daten

befragung_frage7a1_aus <- befragung_frage7a1 |> 
    mutate(antwort = factor(antwort, levels = antwort_levels),
           alter = factor(alter, levels = alter_levels),
           gemeinde_groesse = factor(gemeinde_groesse, 
                                           levels = gemeinde_groesse_level))

# daten speicher

write_csv(befragung_frage7a1_aus, here::here("data/ktzh-bevoelkerungsbefragung-zufriedenheit/KTZH_00001341_00002759_frage7a1.csv"))


```
